### PR TITLE
Rename rollup tests to nollup tests

### PR DESCRIPTION
**Pull request by piotr-cz**
As these are run against [Prefresh-nollup](https://github.com/JoviDeCroock/prefresh/tree/%40prefresh/webpack%402.0.0/packages/nollup) package.

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
I think that'd be a misleading change, `nollup` is the plugin used to introduce `HMR`. Just like `webpack-dev-server` & `next-dev-server` are used for HMR in that regards. Should we switch that naming then as well?

**Comment by piotr-cz** [comment]
Yeah, this is not obvious.

But tests are run via the [nollup cli](https://github.com/JoviDeCroock/prefresh/blob/%40prefresh/webpack%402.0.0/test/constants.js#L14) and integration has been named [Prefresh-nollup](https://github.com/JoviDeCroock/prefresh/tree/%40prefresh/webpack%402.0.0/packages/nollup).

Semantically I'd say that Nollup is not a plugin but individual package that uses [Rollup as a dependency](https://github.com/PepsRyuu/nollup/blob/0.13.11/package.json#L36). It's [readme says](https://github.com/PepsRyuu/nollup/blob/0.13.11/README.md):

> Rollup compatible bundler, designed to be used in development. Using the same Rollup plugins and configuration, it provides a dev server that performs quick builds and rebuilds, and other dev features such as Hot Module Replacement.

For me current state is misleading as it suggests that you can use HMR via Rollup itself.

Maybe Nollup's author @PepsRyuu could give us a hint?

**Comment by JoviDeCroock** [comment]
Webpack is also ran through the webpack-dev-server cli.

**Review by JoviDeCroock — APPROVED** [review]
In essence this change is only affecting tests so I really don't mind, let's do this

**Pull request merged**
