### PR TITLE
(snowpack) - integrate babel plugin

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Resolves https://github.com/JoviDeCroock/prefresh/issues/198

### CODE REVIEW

**Comment by FredKSchott** [comment]
👍 lgtm! Does the plugin handle a file that's already been transformed by Babel? For backwards compat, we added this warning for react in case someone was adding their own babel plugin out of band: 

```

const IS_FAST_REFRESH_ENABLED = /\$RefreshReg\$\(/;
if (IS_FAST_REFRESH_ENABLED.test(contents)) {
    console.warn(
      `[@snowpack/plugin-react-refresh] ${id}\n"react-refresh/babel" babel plugin no longer needed, safe to remove from user babel config.`,
    );
  } 
```

**Comment by JoviDeCroock** [comment]
Yup, it checks whether it's present or not. if it is it just continues

**Comment by FredKSchott** [comment]
👍 awesome. One other thing: https://github.com/JoviDeCroock/prefresh/commit/18ddaceee9fccb53e0a2535f717acdfc1bd4c591#diff-7a57ecc7d2f9659d3bb98d6a1671ab5bR58

Now that the plugin is using @prefresh/babel-plugin 100% internally, can we move it from peer dep to direct dep? Should give you better support for upgrades as well.

**Comment by FredKSchott** [comment]
oh lol, just saw you added it in this PR. looks like now it just needs to be removed as a peerDependencies duplicate

**Pull request merged**
